"""empty message

Revision ID: 931f49c68a8f
Revises: 
Create Date: 2018-12-15 15:32:04.367000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931f49c68a8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('detail_path', sa.String(length=100), nullable=False),
    sa.Column('photo_path', sa.String(length=100), nullable=False),
    sa.Column('is_del', sa.Boolean(), nullable=True),
    sa.Column('is_collection', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
